backend:
  name: github
  repo: CBR0MS/personal-site

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: projects
    label: Project
    folder: projects
    create: true
    fields:
      - { name: path, label: Path, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string }
      - { name: synopsis, label: Synopsis, widget: text }
      - { name: tags, label: Tags, widget: list, default: [] }
      - {
          name: image,
          label: Image,
          widget: image,
          default: "images/default.jpg",
        }
      - {
          name: timeframe,
          label: Timeframe,
          widget: string,
          required: false,
          default: "",
        }
      - {
          name: project_type,
          label: Project Type,
          widget: text,
          required: false,
          default: "",
        }
      - {
          name: tools,
          label: Tools,
          widget: list,
          required: false,
          default: [],
        }
      - { name: disp_order, label: Display Order, widget: number }

      - { name: body, label: Body, widget: markdown }
